### ISSUE TITLE
InvalidCharacterError: Invalid character error from changePassword()

### ISSUE THREAD

**Issue by adelefelicia** [indykite/jarvis-sdk-web-sample-app-react#57]
**Created by: @bradtumy Oct 09 2021 at 01:03 CET**
Last updated: Jul 18 2022 at 11:30 CET
ClickUp ID: IK-1631

When calling the changePassword function I am receiving an invalid character error.

Exception:
Digital Twin ID:  e75c8e57-611d-4a5e-b6b6-c4dca5d75c64
Tenant ID:  696e6479-6b69-4465-8000-030f00000002
Password:  MyNewPassword
changePassword() function called
InvalidCharacterError: Invalid character
    at atob (node:buffer:1236:13)
    at bytesFromBase64 (/Users/bradtumy/develop/indykite/indykite_sample_app/auth_sample/node_modules/@martinkite/jarvis-client-sdk/src/grpc/identity/v1/model.ts:2314:15)
    at Object.fromJSON (/Users/bradtumy/develop/indykite/indykite_sample_app/auth_sample/node_modules/@martinkite/jarvis-client-sdk/src/grpc/identity/v1/model.ts:529:32)
    at Object.fromJSON (/Users/bradtumy/develop/indykite/indykite_sample_app/auth_sample/node_modules/@martinkite/jarvis-client-sdk/src/grpc/identity/v1/identity_management_api.ts:795:34)
    at IdentityClient.changePassword (/Users/bradtumy/develop/indykite/indykite_sample_app/auth_sample/node_modules/@martinkite/jarvis-client-sdk/src/sdk/identity.ts:317:43)
    at changePass (/Users/bradtumy/develop/indykite/indykite_sample_app/auth_sample/src/authn.ts:188:44)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Sample Code:
async function changePass(sdk:IdentityClient) {
  // changePassword(digitaltwinid, tenantid, password)
  // changePasswordByToken

  console.log("Starting changePass()");

  const digitalTwin = getDT(sdk);
  const dt = (await digitalTwin).digitalTwin;

  if (!dt) {
    console.log('Missing DigitalTwin?');
    return;
  }

  const digitalTwinID = dt.id
  const digitalTwinTenantID = dt.tenantId;
  var newPassword = 'MyNewPassword'; 

  // changePassword(digitaltwinid, tenantid, password)
  console.log("Digital Twin ID: ", digitalTwinID);
  console.log("Tenant ID: ", digitalTwinTenantID);
  console.log("Password: ", newPassword);

  console.log("changePassword() function called");
  const changePasswordResponse = await sdk.changePassword(digitalTwinID, digitalTwinTenantID, newPassword);
  console.log("Change Password Resp: ", changePasswordResponse);

Steps to Reproduce:
Install Dependencies (See Environment below)
Create a file called auth.ts with the code sample (from above)
Authenticate a user, store the token in an environment variable called "USER_TOKEN"
Run auth.ts using npm 

Expected Behavior:
Password is set to new password provided
Success response returned

Environment:
tumy-auth-nodejs@0.1 /Users/bradtumy/develop/indykite/indykite_sample_app/auth_sample
├── @grpc/grpc-js@1.3.7
├── @martinkite/jarvis-client-sdk@0.1.7
├── @types/uuid@8.3.1
├── protobufjs@6.11.2
├── require-stack@1.0.2
├── uuid-buffer@1.0.3
├── uuid@8.3.2
└── uuid4@2.0.2

**Comment by adelefelicia** [comment]
**Commented by: @bayegan Oct 11 2021 at 11:38 CET**

@bradtumy : thanks for catching and reporting this. could you add more info - according to bug template:

1) Description

2) Steps to reproduce & supporting documentation

3) Actual behavior & supporting documentation if different than above

4) Expected behavior

5) Version/environment

**Comment by adelefelicia** [comment]
**Commented by: @bradtumy Oct 11 2021 at 21:33 CET**

I've updated the story with the details requested.

**Comment by adelefelicia** [comment]
**Commented by: @dusan-kovacik-profiq Oct 19 2021 at 14:44 CET**

@bradtumy You're using a  ```getDT```  function in your code. Could you share its code as well, please?

**Comment by adelefelicia** [comment]
**Commented by: @bradtumy Oct 19 2021 at 19:48 CET**

That code might be local on my Mac-mini at home. I’m away until Wednesday night but will get it to you as soon as I can.

**Comment by adelefelicia** [comment]
**Commented by: @dusan-kovacik-profiq Oct 25 2021 at 09:38 CET**

@bradtumy, I'm not able to reproduce this bug, I'm getting this response:








```
Starting changePass()
Starting getDT
Digital Twin ID:  039570dd-fbb0-49da-b427-cf4007832087
Tenant ID:  696e6479-6b69-4465-8000-030f00000001
Password:  sdfsdfsdf
changePassword() function called
Change Password Resp:  undefined
```

Could you try to update the packages and run it once more, please?

**Comment by adelefelicia** [comment]
**Commented by: @bradtumy Oct 25 2021 at 21:53 CET**

is working now but 




```
const changePasswordResponse = await sdk.changePassword(digitalTwinID, digitalTwinTenantID, newPassword);
```

doesn't provide a response when a password is successfully changed.  @dusan-kovacik-profiq said he could add a response of "true" when the password is successfully changed.

**Comment by adelefelicia** [comment]
**Commented by: @bradtumy Oct 25 2021 at 21:54 CET**

Slack thread for posterity:



BradBrad  9:13 AM9:13 AM

what is the expected output from this call?  I am getting undefined.const changePasswordResponse = await sdk.changePassword(digitalTwinID, digitalTwinTenantID, newPassword);



Dusan KovacikDusan Kovacik  9:15 AM9:15 AM

According to what's in the source code now, it should return  ```undefined``` . So it should be working correctly unless we don't want it to return something.



BradBrad  9:16 AM9:16 AM

Should we return a success or fail message?



Dusan KovacikDusan Kovacik  9:19 AM9:19 AM

In case there's an error it throws an exception. Otherwise it probably doesn't matter what we return. But I can see, that  ```changePasswordOfDigitalTwin```  returns  ```true```  when the password is changed successfully. So I can update this function to return  ```true```  as well.



BradBrad  9:20 AM9:20 AM

I think either way is fine but we should be consistent



Dusan KovacikDusan Kovacik  9:21 AM9:21 AM

Yeah, I think so as well. So I will update the function so that it returns  ```true```  too.



BradBrad  9:21 AM9:21 AM

ok thank you

**Comment by adelefelicia** [comment]
**Commented by: @bayegan Oct 26 2021 at 01:14 CET**

@dusan-kovacik-profiq : will you complete this for moon sprint?
